
// Objective-C API for talking to the following Go packages
//
//	github.com/mandelmonkey/lndmobile/lightning
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Lightning_FRAMEWORK_H__
#define __Lightning_FRAMEWORK_H__

#include "Lightning.objc.h"
#include "Universe.objc.h"

#endif
